### ISSUE TITLE
CAN frame <> signal communication interface

### ISSUE THREAD

**Issue by bvogler23** [vectorgrp/sil-kit-fmu-importer#5]
Hello,

I have a project in which I have a VECU silkit participant that is communicating via CAN frames. I would like to connect it to an fmu using sil-kit-fmu-importer, and via an fmu-importer-communication-interface-file, define the translation between CAN frames and signals that the 2 participants expect.

For example, the VECU might output a CAN frame (ID: 0x100) that has a command value at data bit 0, of length 16 bits and byte order little endian. The fmu plant model is expecting an input signal of type int16_t.

Would it be possible to use the communication interface description file to extract the data/signal from the inbound CAN frame, and pass it to the fmu, and conversely, take the output of the fmu and package it into an outbound CAN frame?
If so, are there any example YAML files to help get me started? Or is there another method to achieve this?

Thanks.

**Comment by Jean-ThomasMasse** [comment]
SIL Kit's CAN capabilities are not supported for the FMU Importer right now. The interface description file only maps FMI variables to topics, not CAN networks. We are currently studying if the FMU Importer will implement the [FMI Layered Standard for Network Communication](https://github.com/modelica/fmi-ls-bus) instead, if it comes to fruition (and adoption).

In the meantime you could code your own additional participant to bridge a pair of SIL Kit topics and a CAN network. You can use pieces of [Vector SIL Kit Adapter for QEMU](https://github.com/vectorgrp/sil-kit-adapters-qemu) (for the SIL Kit topics) and [Vector SIL Kit Adapter for virtual CAN](https://github.com/vectorgrp/sil-kit-adapters-vcan)(for the SIL Kit CAN simulated network), leaving out the QEMU and socketCAN parts of those projects.
